mysite/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/',include('polls.urls')),
]

polls/urls.py
from django.urls import path
from django.conf.urls import url
from polls import views

app_name="polls"
urlpatterns = [
    path('', views.index,name="index"),
    path('<int:question_id>/', views.detail, name='detail'),
    path('<int:question_id>/results/',views.results,name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    path('<int:question_id>/form/', views.form, name='form'),
]

polls/models.py
from django.db import models
from django.utils import timezone
import datetime

class Question(models.Model):

    question_text = models.CharField(max_length=100)
    pub_date = models.DateTimeField(" published date")

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
        was_published_recently.admin_order_field = 'pub_date'
        was_published_recently.boolean = True
        was_published_recently.short_description = 'Published recently?'

class Choice(models.Model):
    question = models.ForeignKey("Question", on_delete=models.CASCADE)
    choice_text =  models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

polls/views.py
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from polls.models import Question,Choice
from django.template import loader
from django.http import Http404
from django.urls import reverse
from django.utils import timezone
from django.views.generic import ListView

def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    # template = loader.get_template('polls/index.html')
    output = ', '.join([q.question_text for q in latest_question_list])
    context={
        'latest_question_list':latest_question_list,
    }
    # return HttpResponse(template.render(context, request))
    return render(request,'polls/index.html',context)


def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    context = {
        'question': question ,
    }
    return render(request,'polls/detail.html',context)

def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.html', {'question': question})

def vote(request, question_id):
    return HttpResponse("You're voting on question %s." % question_id)

def form(request,question_id):
    question = get_object_or_404(Question,pk=question_id)

    try:
        selected_choice =  question.choice_set.get(pk=request.POST['choice'])

    except(KeyError, Choice.DoesNotExist):
        context={
        'question':question,
        'error_message': "You didn't select a choice.",
        }
        return render(request,'polls/form.html',context)
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

class IndexView(ListView):
   
    template_name = "polls/index.html"
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:5]
    

polls/templates/polls/detail.html
<html>
  <head>
    <meta charset="utf-8">
    <title>index</title>
    {% load static %}
      <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">

  </head>
  <body>
    {% if question %}
      <ul>
    
          <a href="{% url 'polls:results' question.id %}">{{ question.question_text }}</a>
        
      
        {% for choice in question.choice_set.all %}
        <li>{{ choice.choice_text }}</li>
        {% endfor %}
      </ul>
   
    {% else %}
      <p>error</p>
    {% endif %}

  </body>
</html>
    

polls/templates/polls/form.html
    {%load static %}
<html>
  <head>
    <meta charset="utf-8">
    <title>index</title>

      <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css'%}">
  </head>
  <body>
    <form action={%url 'polls:form' question.id %} method="POST" >
    {% csrf_token %}
    {% if error_message %} <p><strong>{{ error_message }}</strong></p> {% endif %}
    {%for choice in question.choice_set.all%}
        <input type="radio" name="choice" id="choice{{forloop.counter}}" value="{{choice.id}}"
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
        {%endfor%}
        <input type="submit" value="Vote">
    </form>

  </body>
</html>

polls/templates/polls/index.html
{%load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>index</title>
    <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css'%}">
  </head>
  <body>
    {% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
       <li> <a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
    {% else %}
        <p>No polls are available.</p>
    {% endif %}

  </body>
</html>
    

polls/templates/polls/results.html
<!DOCTYPE html>

<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>
    
        
        <h1>{{question.question_text}}</h1>
        <ul>
            {%for choice in question.choice_set.all%}
                <li> {{choice.choice_text}} -- {{choice.votes}} vote{{choice.votes|pluralize}}</li>
            {%endfor%}
        </ul>
        <a href="{% url 'polls:form' question.id %}">Vote again?</a>
    </body>
</html>